/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void roll(int n) {
        int[] result = new int[n];
        ArrayList<Integer> number = new ArrayList<>();
        for (int i = 0; i < result.length; i++) {
            int random = (int) Math.ceil(Math.random() * 6);
            number.add(random);

        }
        System.out.println(number);
    }

    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }

        // no duplicate is found
        return false;
    }

    public static double Average(int[] array) {
        double sum = 0;
        for (int value : array) {
            sum += value;
        }
        return (sum / array.length);
    }


    public static double arraysLowestAav(int[][] arr) {

//        ArrayList <Double> avarg = new ArrayList<>();
        double[] avarg = new double[arr.length];

        double finalAv = 0;
        for (int i = 0; i < arr.length; i++) {
            double sum = 0;
            double arrLength = 0;
            for (int j = 0; j < arr[i].length; j++) {

                sum += arr[i][j];
            }
            avarg[i] = sum / arr[i].length;
        }
        finalAv=avarg[0];
        for (int i = 1; i < avarg.length; i++) {

            if (avarg[i] < finalAv) {
                finalAv = avarg[i];
            }

        }
        return finalAv;
    }


}
