/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Library testfun = new Library();
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "should return 'true'");
    }

            @Test
    public void testroll() {

        int numRolls = 4;
        assertEquals(numRolls,testfun.roll(numRolls).length,"correct");
    }
    @Test
    public void testAverage(){
        int [] arr ={1,1,1};
        int avreg= 1;
        assertEquals( avreg, testfun.Average(arr));
    }

    @Test
    public void testContainsDuplicate() {
        int[] testArr = new int[]{1, 2, 3, 4, 4, 5};

        assertTrue(testfun.containsDuplicates(testArr), " should return 'true'");

    }
    @Test
    public void testArraysLowestAav() {
        int[][] testArr = new int[][]{
                {66, 64, 58, 65, 71, 57, 60}, // 63.0
                {57, 65, 65, 70, 72, 65, 51}, // 63.5714285714
                {55, 54, 60, 53, 59, 57, 61}, // 57.0
                {65, 56, 55, 52, 55, 62, 57} // 57.4285714286
        };
        assertArrayEquals(Library.arraysLowestAav(testArr), testArr[2],"lowest average is arr at index 2");
    }
}
