/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab6;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    void Restaurant(){
        Restaurant testRest =new Restaurant("kfc","$",2);

        assertEquals("Restaurant{name='kfc', num=2, priceCategory='$'}",testRest.toString(),"ssssssssss");
    }
    @Test
    void Review(){
        Review testRev =new Review("good","sanaa",5);

        assertEquals("Review{body='good', author='sanaa', numStar=5}",testRev.toString(),"ssssssssss");
    }
}
